In [95]:
import numpy as np
import pandas as pd
from glob import glob
# merge csv files
def merge_files(SOURCE):
    files_list = sorted(glob(SOURCE + '/*'))
    df_list = []
    for num, path in enumerate(files_list):
        df = pd.read_csv(path)
        df = df.drop(['business_id','city','date','funny','state','useful','cool'], axis=1)
        df = df.rename(columns={'stars_y':'review_stars'})
        df_list.append(df)
    df = pd.concat(df_list, join='outer', ignore_index=True, axis=0, sort=True)
    return df

SOURCE = 'AZ_top20_categories_csv'
yelp = merge_files(SOURCE)
yelp = yelp.drop(['stars','stars_x'], axis=1)
yelp = yelp.rename(columns={'review_stars':'rating'})
print(yelp.shape)
yelp.head()

(3010486, 3)

    categories  rating                                               text
0  Active Life       5  Douglas W. has it right.  You're basically on ...
1  Active Life       2  Nice place, but they think nothing of running ...
2  Active Life       5  Absolutely beautiful! I think I could stay her...
3  Active Life       5  I see 4 star ratings and can't figure out how ...
4  Active Life       1  In the 8 years I have owned my mountain bike, ...

In [154]:
yelp.dtypes

categories    object
rating         int64
text          object
dtype: object

In [28]:
yelp.isnull().sum()

categories    0
rating        0
text          0
dtype: int64

In [34]:
# yelp['rating'] = yelp['rating'].map({4: 5, 2: 1, 3: 1})
yelp = yelp.drop(['new_rating'], axis=1)
yelp['rating'] = yelp['rating'].replace({4:5, 2:1, 3:1})
yelp['rating'].value_counts()

5    2044942
1     965544
Name: rating, dtype: int64

In [36]:
yelp.head()

    categories  rating                                               text
0  Active Life       5  Douglas W. has it right.  You're basically on ...
1  Active Life       1  Nice place, but they think nothing of running ...
2  Active Life       5  Absolutely beautiful! I think I could stay her...
3  Active Life       5  I see 4 star ratings and can't figure out how ...
4  Active Life       1  In the 8 years I have owned my mountain bike, ...

In [31]:
import pandas as pd
import spacy
import scattertext

In [17]:
yelp['categories'].value_counts().index

Index(['Restaurants', 'Food', 'Nightlife', 'Shopping', 'Beauty & Spas',
       'Home Services', 'Event Planning & Services', 'Automotive',
       'Health & Medical', 'Local Services', 'Fast Food', 'Active Life',
       'Auto Repair', 'Doctors', 'Hair Salons', 'Home & Garden', 'Fashion',
       'Professional Services', 'Real Estate', 'Contractors'],
      dtype='object')

In [54]:
import pandas as pd
pd.set_option('display.max_columns', 500) # Make sure we can see all of the columns
pd.set_option('display.max_rows', 200)

In [96]:
Shopping_yelp = yelp[yelp['categories']=='Shopping']
Shopping_yelp['rating'] = Shopping_yelp['rating'].astype('float')
Shopping_yelp['rating'] = Shopping_yelp['rating'].astype('str')
print(Shopping_yelp.shape)
Shopping_yelp.head()

(166680, 3)

        categories rating                                               text
2843806   Shopping    1.0  Went out of my way to get paint at this store ...
2843807   Shopping    1.0  This company tried deliver flowers to our home...
2843808   Shopping    1.0  This the worst flower place that I've ever enc...
2843809   Shopping    5.0  A great spot to grab a shake right at 51 Freew...
2843810   Shopping    5.0  We were just in Arizona visiting family and st...

In [111]:
Shopping_yelp['rating'] = Shopping_yelp['rating'].replace({'4.0':'5.0', '2.0':'1.0', '3.0':'1.0'})
Shopping_yelp['rating'].value_counts()/len(Shopping_yelp['rating'])

5.0    0.67146
1.0    0.32854
Name: rating, dtype: float64

In [101]:
Shopping_yelp['rating'].value_counts()/len(Shopping_yelp['rating'])

5.0    0.542945
1.0    0.211225
4.0    0.128516
3.0    0.059209
2.0    0.058105
Name: rating, dtype: float64

In [105]:
Shopping_yelp['rating'].value_counts()

5.0    90498
1.0    35207
4.0    21421
3.0     9869
2.0     9685
Name: rating, dtype: int64

In [104]:
Shopping_yelp_sample = Shopping_yelp.sample(frac=.5)
print(Shopping_yelp_sample.shape)
Shopping_yelp_sample['rating'].value_counts()/len(Shopping_yelp_sample['rating'])

(83340, 3)

5.0    0.540605
1.0    0.212683
4.0    0.128762
3.0    0.059827
2.0    0.058123
Name: rating, dtype: float64

In [108]:
Shopping_yelp_sample.dtypes

categories    object
rating        object
text          object
dtype: object

In [109]:
Shopping_yelp_sample['rating'] = Shopping_yelp_sample['rating'].replace({'4.0':'5.0', '2.0':'1.0', '3.0':'1.0'})
Shopping_yelp_sample['rating'].value_counts()

5.0    55785
1.0    27555
Name: rating, dtype: int64

In [110]:
Shopping_yelp_sample['rating'].value_counts()/len(Shopping_yelp_sample['rating'])

5.0    0.669366
1.0    0.330634
Name: rating, dtype: float64

In [41]:
nlp = spacy.load("en_core_web_lg")

In [112]:
# add stop words
with open('stopwords.txt', 'r') as f:
    str = f.read()
    set_stopwords = set(str.split('\n'))
nlp.Defaults.stop_words |= set_stopwords

In [ ]:
corpus = (scattertext.CorpusFromPandas(Shopping_yelp_sample, 
                                      category_col='rating', 
                                      text_col='text',
                                      nlp=nlp)
          .build()
          .remove_terms(nlp.Defaults.stop_words, ignore_absences=True)
         )

In [ ]:
term_freq_df = corpus.get_term_freq_df()
term_freq_df['highratingscore'] = corpus.get_scaled_f_scores('5.0')
term_freq_df['poorratingscore'] = corpus.get_scaled_f_scores('1.0')

df_high = term_freq_df.sort_values(by='highratingscore', 
                                   ascending = False)
df_poor = term_freq_df.sort_values(by='poorratingscore', 
                                   ascending=False)

# df_high = df_high[['highratingscore', 'poorratingscore']]
df_high['highratingscore'] = round(df_high['highratingscore'], 2)
df_high['poorratingscore'] = round(df_high['poorratingscore'], 2)
df_high = df_high.reset_index(drop=False)
# df_high = df_high.head(20)

# df_poor = df_poor[['highratingscore', 'poorratingscore']]
df_poor['highratingscore'] = round(df_poor['highratingscore'], 2)
df_poor['poorratingscore'] = round(df_poor['poorratingscore'], 2)
df_poor = df_poor.reset_index(drop=False)
# df_poor = df_poor.head(20)

# df_terms = pd.concat([df_high, df_poor],
#                      ignore_index=True)
# df_terms

In [ ]:
Shopping_yelp_sample_high = df_high
Shopping_yelp_sample_poor = df_poor

In [119]:
Shopping_yelp_sample_high.sort_values(by='5.0 freq', ascending = False).head(100)

,term,5.0 freq,1.0 freq,highratingscore,poorratingscore
1245604,store,18755,17941,0.12,0.88
1244761,service,15985,13303,0.14,0.86
2483,good,12253,6143,0.91,0.09
2685,new,11188,5889,0.90,0.10
453,friendly,10763,1819,0.97,0.03
1282,staff,10484,3434,0.94,0.06
3255,and the,10252,6134,0.89,0.11
558,best,9815,1912,0.97,0.03
406,helpful,9431,1463,0.97,0.03
452,recommend,9158,1543,0.97,0.03
1247053,customer,8848,11209,0.09,0.91
4348,for a,8388,6051,0.87,0.13
1691,nice,8344,3285,0.93,0.07
2472,experience,8294,4140,0.91,0.09
2933,work,8286,4650,0.90,0.10
3179,if you,8234,4851,0.89,0.11
1245634,went,8079,7766,0.12,0.88
2405,shop,7982,3911,0.91,0.09
2444,this place,7938,3933,0.91,0.09
262,a great,7928,909,0.98,0.02
1244757,i 'm,7622,6342,0.14,0.86
1726,they have,7579,3031,0.93,0.07
1246464,to the,7544,8476,0.10,0.90
2636,i 've,7505,3904,0.91,0.09
1244963,for the,7379,6336,0.13,0.87
952,selection,7295,1971,0.95,0.05
1247773,$,7074,10771,0.08,0.92
2399,looking,7030,3440,0.91,0.09
1244837,day,6993,5891,0.13,0.87
1549,prices,6825,2521,0.93,0.07
281,the best,6777,805,0.98,0.02
3756,need,6652,4356,0.88,0.12
1246612,customer service,6603,7624,0.10,0.90
1245508,know,6513,6122,0.12,0.88
1246246,on the,6500,7039,0.11,0.89
1245571,to get,6486,6164,0.12,0.88
403,definitely,6474,998,0.98,0.02
4369,and they,6464,4677,0.87,0.13
2717,is a,6417,3414,0.90,0.10
2072,found,6209,2771,0.92,0.08
3515,this is,6127,3842,0.89,0.11
1245375,going,6114,5617,0.12,0.88
1245560,i would,6098,5783,0.12,0.88
1245057,help,6078,5285,0.13,0.87
4227,with the,6059,4290,0.87,0.13
1245900,that i,5988,6033,0.11,0.89
3367,right,5902,3604,0.89,0.11
1246053,people,5890,6118,0.11,0.89
4336,home,5887,4239,0.87,0.13
1244075,i am,5864,4394,0.15,0.85
3935,price,5855,3956,0.88,0.12
2950,have a,5847,3293,0.90,0.10
1246982,the store,5817,7270,0.09,0.91
1244384,came,5656,4430,0.14,0.86
1247088,to be,5498,7028,0.09,0.91
2528,years,5486,2776,0.91,0.09
1246700,when i,5485,6439,0.10,0.90
2980,sure,5471,3102,0.90,0.10
85,highly,5458,322,0.99,0.01
1244915,location,5441,4635,0.13,0.87
2019,little,5378,2368,0.92,0.08
1245205,come,5296,4718,0.13,0.87
2553,had a,5277,2689,0.91,0.09
1245271,way,5220,4715,0.13,0.87
2546,&,5190,2641,0.91,0.09
1244214,items,5170,3948,0.15,0.85
3390,needed,5170,3171,0.89,0.11
373,i love,5099,742,0.98,0.02
1580,job,5094,1910,0.93,0.07
328,thank,5087,677,0.98,0.02
1244261,they are,5084,3911,0.14,0.86
802,happy,5017,1200,0.96,0.04
3192,a few,4983,2941,0.89,0.11
1244903,i will,4974,4232,0.13,0.87
1038,the staff,4954,1415,0.95,0.05
4138,look,4946,3453,0.87,0.13
1244210,they were,4924,3760,0.15,0.85
1247,was very,4854,1557,0.94,0.06
3558,with a,4853,3065,0.88,0.12
582,super,4742,942,0.97,0.03
2897,things,4715,2628,0.90,0.10
1650,looking for,4659,1801,0.93,0.07
1651,quality,4607,1782,0.93,0.07
1245052,wanted,4606,3998,0.13,0.87
2799,for my,4561,2473,0.90,0.10
207,thank you,4557,452,0.99,0.01
1245926,buy,4539,4598,0.11,0.89
240,friendly and,4485,485,0.98,0.02
4364,it is,4450,3216,0.87,0.13
961,clean,4390,1194,0.95,0.05
2564,all the,4360,2230,0.91,0.09
317,professional,4338,569,0.98,0.02
1244193,better,4313,3285,0.15,0.85
1244358,was a,4312,3366,0.14,0.86
10,highly recommend,4308,102,1.00,0.00
2252,feel,4285,2012,0.92,0.08
3169,lot,4285,2519,0.89,0.11
4444,in a,4267,3122,0.87,0.13
3249,what i,4250,2540,0.89,0.11
3003,/,4232,2409,0.90,0.10

In [118]:
Shopping_yelp_sample_poor.sort_values(by='1.0 freq', ascending = False).head(100)

,term,5.0 freq,1.0 freq,highratingscore,poorratingscore
3886,store,18755,17941,0.12,0.88
4729,service,15985,13303,0.14,0.86
2437,customer,8848,11209,0.09,0.91
408,said,3272,11054,0.03,0.97
1717,$,7074,10771,0.08,0.92
3026,to the,7544,8476,0.10,0.90
3856,went,8079,7766,0.12,0.88
2878,customer service,6603,7624,0.10,0.90
2508,the store,5817,7270,0.09,0.91
3244,on the,6500,7039,0.11,0.89
2402,to be,5498,7028,0.09,0.91
622,asked,2534,6832,0.04,0.96
1188,called,3631,6772,0.06,0.94
2790,when i,5485,6439,0.10,0.90
4733,i 'm,7622,6342,0.14,0.86
4527,for the,7379,6336,0.13,0.87
3919,to get,6486,6164,0.12,0.88
1247007,good,12253,6143,0.91,0.09
1246235,and the,10252,6134,0.89,0.11
3982,know,6513,6122,0.12,0.88
3437,people,5890,6118,0.11,0.89
1245142,for a,8388,6051,0.87,0.13
3590,that i,5988,6033,0.11,0.89
1305,phone,3369,5965,0.06,0.94
4653,day,6993,5891,0.13,0.87
1246805,new,11188,5889,0.90,0.10
3930,i would,6098,5783,0.12,0.88
4115,going,6114,5617,0.12,0.88
2092,so i,3922,5387,0.08,0.92
426,manager,1595,5287,0.03,0.97
4433,help,6078,5285,0.13,0.87
1246311,if you,8234,4851,0.89,0.11
4285,come,5296,4718,0.13,0.87
4219,way,5220,4715,0.13,0.87
2658,business,3905,4707,0.10,0.90
1245121,and they,6464,4677,0.87,0.13
1246557,work,8286,4650,0.90,0.10
4575,location,5441,4635,0.13,0.87
3564,buy,4539,4598,0.11,0.89
5106,came,5656,4430,0.14,0.86
5415,i am,5864,4394,0.15,0.85
1245734,need,6652,4356,0.88,0.12
1601,minutes,2716,4298,0.07,0.93
1245263,with the,6059,4290,0.87,0.13
2344,company,3275,4246,0.09,0.91
1245154,home,5887,4239,0.87,0.13
4587,i will,4974,4232,0.13,0.87
1247018,experience,8294,4140,0.91,0.09
1103,had to,2135,4126,0.06,0.94
2708,i do,3412,4068,0.10,0.90
811,money,1764,4066,0.05,0.95
4438,wanted,4606,3998,0.13,0.87
45,rude,315,3964,0.01,0.99
1245555,price,5855,3956,0.88,0.12
5276,items,5170,3948,0.15,0.85
1247046,this place,7938,3933,0.91,0.09
1247085,shop,7982,3911,0.91,0.09
5229,they are,5084,3911,0.14,0.86
3409,i did,3743,3910,0.11,0.89
1246854,i 've,7505,3904,0.91,0.09
1663,order,2484,3848,0.07,0.93
1245975,this is,6127,3842,0.89,0.11
2832,have to,3291,3838,0.10,0.90
5280,they were,4924,3760,0.15,0.85
1704,if i,2429,3711,0.08,0.92
3110,i went,3348,3706,0.10,0.90
3961,but i,3868,3648,0.12,0.88
3604,i could,3601,3617,0.11,0.89
1246123,right,5902,3604,0.89,0.11
1328,left,2049,3594,0.06,0.94
3407,out of,3345,3495,0.11,0.89
1245352,look,4946,3453,0.87,0.13
1247091,looking,7030,3440,0.91,0.09
1248208,staff,10484,3434,0.94,0.06
1246773,is a,6417,3414,0.90,0.10
4314,this store,3814,3382,0.13,0.87
5132,was a,4312,3366,0.14,0.86
1182,bad,1800,3361,0.06,0.94
860,return,1505,3352,0.05,0.95
941,customers,1583,3350,0.05,0.95
2268,days,2533,3334,0.09,0.91
550,told me,1155,3329,0.04,0.96
2137,employees,2450,3327,0.08,0.92
3034,going to,2944,3304,0.10,0.90
1246540,have a,5847,3293,0.90,0.10
5297,better,4313,3285,0.15,0.85
1247799,nice,8344,3285,0.93,0.07
1541,would be,2011,3243,0.07,0.93
3399,times,3097,3240,0.11,0.89
1245126,it is,4450,3216,0.87,0.13
1246100,needed,5170,3171,0.89,0.11
2052,that they,2270,3155,0.08,0.92
1018,i called,1548,3129,0.06,0.94
1245046,in a,4267,3122,0.87,0.13
1246510,sure,5471,3102,0.90,0.10
3436,think,2958,3073,0.11,0.89
1245932,with a,4853,3065,0.88,0.12
5296,to go,4020,3062,0.15,0.85
264,i asked,686,3053,0.02,0.98
1247764,they have,7579,3031,0.93,0.07

In [94]:
Auto_Repair_yelp_high.sort_values(by='5.0 freq', ascending = False).head(100)

                    term  5.0 freq  1.0 freq  highratingscore  poorratingscore
2976                 car     40357     41815             0.87             0.13
1849             service     26490     19259             0.91             0.09
1219                work     15144      8105             0.93             0.07
2299              my car     14244     12133             0.89             0.11
2116                 new     10707      8581             0.90             0.10
1172          experience     10665      5513             0.94             0.06
1108                shop      9506      4745             0.94             0.06
371            recommend      9271      2003             0.98             0.02
2210              i have      8976      7421             0.89             0.11
3098              of the      8714      9344             0.87             0.13
881475           vehicle      8222     10800             0.13             0.87
1407                good      8198      4861             0.92             0.08
2212            customer      8195      6781             0.89             0.11
2823                 got      8079      7981             0.88             0.12
2671                took      8012      7590             0.88             0.12
204               honest      7863      1033             0.99             0.01
881400            it was      7809     10111             0.13             0.87
881795        dealership      7487     10499             0.12             0.88
609                 guys      7314      2283             0.96             0.04
3466                went      7259      8467             0.85             0.15
882585           the car      7244     12467             0.10             0.90
2799               price      7227      7094             0.88             0.12
272                 best      7209      1212             0.98             0.02
2938               for a      7024      7202             0.87             0.13
1028              repair      6959      3279             0.94             0.06
2320             and the      6826      5857             0.89             0.11
881080            to get      6714      8123             0.14             0.86
608                 auto      6492      2020             0.96             0.04
1999              needed      6475      5011             0.90             0.10
183             friendly      6427       782             0.99             0.01
2899            and they      6387      6468             0.87             0.13
882165               oil      6387      9750             0.11             0.89
881813            on the      6204      8730             0.12             0.88
3272             i would      5933      6624             0.86             0.14
3178                know      5852      6404             0.86             0.14
2656            with the      5843      5516             0.88             0.12
882047            to the      5798      8598             0.11             0.89
3307               going      5724      6444             0.86             0.14
1141                care      5651      2872             0.94             0.06
239              a great      5648       839             0.98             0.02
189                thank      5629       694             0.99             0.01
2137               right      5617      4531             0.90             0.10
881208               day      5596      6964             0.13             0.87
2025                need      5450      4258             0.90             0.10
814                  job      5391      2124             0.95             0.05
881663             to be      5329      7247             0.12             0.88
881666           for the      5318      7241             0.12             0.88
94                highly      5255       414             0.99             0.01
208             the best      5251       692             0.99             0.01
2084              i will      5210      4136             0.90             0.10
1298               i 've      5172      2892             0.93             0.07
883869                 $      5162     16854             0.05             0.95
1732               on my      5126      3563             0.91             0.09
881757            that i      5114      7108             0.12             0.88
1135               years      5110      2589             0.94             0.06
2354           they were      5051      4379             0.89             0.11
134            thank you      5002       482             0.99             0.01
1857    customer service      4982      3628             0.91             0.09
3020                came      4945      5198             0.87             0.13
1694                cars      4940      3378             0.91             0.09
882333            when i      4906      7780             0.10             0.90
882813            called      4886      8981             0.09             0.91
1527               found      4742      2991             0.92             0.08
2704                 way      4731      4526             0.88             0.12
1723               had a      4569      3164             0.91             0.09
882090            change      4563      6834             0.11             0.89
1879              he was      4560      3351             0.91             0.09
289               thanks      4534       795             0.98             0.02
293           definitely      4468       798             0.98             0.02
3268         the service      4463      4976             0.86             0.14
3456                deal      4449      5180             0.86             0.14
209         professional      4427       586             0.99             0.01
880933          business      4419      5195             0.14             0.86
881357              i 'm      4411      5666             0.13             0.87
2194            they are      4409      3631             0.90             0.10
1821                sure      4375      3155             0.91             0.09
2839                i am      4372      4340             0.87             0.13
882163             sales      4313      6582             0.11             0.89
587             was very      4172      1258             0.96             0.04
3393              wanted      4143      4761             0.86             0.14
221              helpful      4139       575             0.99             0.01
1092                nice      4138      2038             0.94             0.06
17      highly recommend      4085       160             1.00             0.00
507              care of      4039      1091             0.97             0.03
1771               of my      4002      2830             0.91             0.09
883960              said      3996     14426             0.04             0.96
1484              buying      3929      2424             0.92             0.08
1520             looking      3908      2455             0.92             0.08
517                happy      3891      1076             0.97             0.03
2439              if you      3869      3436             0.89             0.11
881828        oil change      3833      5416             0.12             0.88
994              repairs      3816      1747             0.94             0.06
1995               fixed      3779      2921             0.90             0.10
881430             truck      3773      4909             0.13             0.87
881006            people      3762      4478             0.14             0.86
2833               was a      3731      3694             0.87             0.13
1777                gave      3684      2612             0.91             0.09
2520               a new      3633      3300             0.88             0.12
2700              with a      3631      3467             0.88             0.12
1611            mechanic      3625      2395             0.92             0.08

In [93]:
Auto_Repair_yelp_poor.sort_values(by='1.0 freq', ascending = False).head(100)

                    term  5.0 freq  1.0 freq  highratingscore  poorratingscore
881356               car     40357     41815             0.87             0.13
882483           service     26490     19259             0.91             0.09
463                    $      5162     16854             0.05             0.95
372                 said      3996     14426             0.04             0.96
1747             the car      7244     12467             0.10             0.90
882033            my car     14244     12133             0.89             0.11
2857             vehicle      8222     10800             0.13             0.87
2537          dealership      7487     10499             0.12             0.88
2932              it was      7809     10111             0.13             0.87
2167                 oil      6387      9750             0.11             0.89
881234            of the      8714      9344             0.87             0.13
1519              called      4886      8981             0.09             0.91
2519              on the      6204      8730             0.12             0.88
2285              to the      5798      8598             0.11             0.89
882216               new     10707      8581             0.90             0.10
880866              went      7259      8467             0.85             0.15
3252              to get      6714      8123             0.14             0.86
883113              work     15144      8105             0.93             0.07
881509               got      8079      7981             0.88             0.12
1999              when i      4906      7780             0.10             0.90
881661              took      8012      7590             0.88             0.12
937              manager      3259      7500             0.07             0.93
882122            i have      8976      7421             0.89             0.11
2669               to be      5329      7247             0.12             0.88
2666             for the      5318      7241             0.12             0.88
881394             for a      7024      7202             0.87             0.13
2575              that i      5114      7108             0.12             0.88
881533             price      7227      7094             0.88             0.12
3124                 day      5596      6964             0.13             0.87
2242              change      4563      6834             0.11             0.89
516                asked      2195      6794             0.05             0.95
882120          customer      8195      6781             0.89             0.11
881060           i would      5933      6624             0.86             0.14
2169               sales      4313      6582             0.11             0.89
881433          and they      6387      6468             0.87             0.13
881025             going      5724      6444             0.86             0.14
881154              know      5852      6404             0.86             0.14
1816                so i      3560      5979             0.10             0.90
882012           and the      6826      5857             0.89             0.11
2975                i 'm      4411      5666             0.13             0.87
881676          with the      5843      5516             0.88             0.12
883160        experience     10665      5513             0.94             0.06
2504          oil change      3833      5416             0.12             0.88
981              told me      2349      5292             0.07             0.93
806                later      2145      5277             0.07             0.93
881312              came      4945      5198             0.87             0.13
3399            business      4419      5195             0.14             0.86
880876              deal      4449      5180             0.86             0.14
882333            needed      6475      5011             0.90             0.10
881064       the service      4463      4976             0.86             0.14
2902               truck      3773      4909             0.13             0.87
882925              good      8198      4861             0.92             0.08
1018              had to      2157      4788             0.07             0.93
2659                come      3506      4782             0.12             0.88
880939            wanted      4143      4761             0.86             0.14
883224              shop      9506      4745             0.94             0.06
1383               hours      2445      4718             0.09             0.91
3034               a car      3589      4554             0.13             0.87
1667                 buy      2574      4533             0.09             0.91
882195             right      5617      4531             0.90             0.10
881628               way      4731      4526             0.88             0.12
3326              people      3762      4478             0.14             0.86
1118           that they      2103      4476             0.08             0.92
2304                 guy      3016      4452             0.11             0.89
877                 left      1867      4428             0.07             0.93
881978         they were      5051      4379             0.89             0.11
881493              i am      4372      4340             0.87             0.13
882307              need      5450      4258             0.90             0.10
3269               i did      3484      4193             0.14             0.86
1281                tell      2082      4150             0.08             0.92
882248            i will      5210      4136             0.90             0.10
1019            would be      1840      4084             0.07             0.93
668             that the      1524      4071             0.06             0.94
1902         appointment      2466      4037             0.10             0.90
1164               phone      1918      4009             0.08             0.92
3339               drive      3323      3948             0.14             0.86
1467            warranty      2112      3941             0.09             0.91
1206                days      1912      3935             0.08             0.92
2737            going to      2920      3923             0.12             0.88
1683            i called      2212      3881             0.09             0.91
2410             minutes      2657      3828             0.12             0.88
129             was told       600      3777             0.02             0.98
1290               money      1889      3757             0.08             0.92
3085                tire      2995      3754             0.13             0.87
881269           problem      3526      3747             0.87             0.13
2592              dealer      2694      3734             0.12             0.88
2792            they did      2798      3718             0.12             0.88
881499             was a      3731      3694             0.87             0.13
881176        this place      3380      3679             0.86             0.14
3362             i could      3103      3673             0.14             0.86
882138          they are      4409      3631             0.90             0.10
882475  customer service      4982      3628             0.91             0.09
1244                 bad      1787      3615             0.08             0.92
3387             we were      3064      3608             0.14             0.86
2299              i went      2435      3601             0.11             0.89
1347             did not      1835      3580             0.08             0.92
1617                if i      2005      3575             0.09             0.91
882600             on my      5126      3563             0.91             0.09
1995             have to      2229      3540             0.10             0.90
881149           this is      3220      3525             0.86             0.14

In [86]:
Hair_Salons_yelp_high.sort_values(by='5.0 freq', ascending = False).head(100)

                    term  5.0 freq  1.0 freq  highratingscore  poorratingscore
1502                hair     42750     15626             0.92             0.08
1470             my hair     22150      7970             0.92             0.08
1031               salon     16158      4370             0.94             0.06
1565                 cut     15273      5798             0.92             0.08
1171              i have     10864      3286             0.93             0.07
1334               color      9242      3090             0.93             0.07
1763             stylist      8204      3432             0.91             0.09
195                 best      7913       571             0.99             0.01
766                i 've      7710      1642             0.95             0.05
626                  job      7649      1358             0.96             0.04
2034               for a      6987      3324             0.89             0.11
302            recommend      6919       687             0.98             0.02
1555                good      6604      2498             0.92             0.08
225              a great      6559       516             0.98             0.02
1734             haircut      6482      2672             0.91             0.09
1643               going      6474      2550             0.91             0.09
488                years      6420       917             0.97             0.03
242               she is      6044       499             0.98             0.02
1800                i 'm      6007      2561             0.90             0.10
133             the best      5877       328             0.99             0.01
317             friendly      5772       592             0.98             0.02
749                  new      5665      1185             0.96             0.04
557288            in the      5538      3304             0.15             0.85
1198                look      5271      1629             0.93             0.07
2472              of the      5210      2935             0.87             0.13
1253             and she      5111      1621             0.93             0.07
1749          experience      5109      2126             0.91             0.09
280           definitely      5077       468             0.98             0.02
1337                i am      5063      1695             0.93             0.07
557224               got      5003      2929             0.15             0.85
557261            wanted      4990      2952             0.15             0.85
1454              what i      4959      1767             0.92             0.08
2334              to get      4672      2511             0.88             0.12
557353           service      4616      2811             0.15             0.85
557866       appointment      4616      3352             0.13             0.87
480                happy      4522       635             0.97             0.03
1832             and the      4505      1957             0.90             0.10
1182                work      4476      1366             0.93             0.07
1025             looking      4448      1198             0.94             0.06
1465                nice      4446      1593             0.92             0.08
52                highly      4390       133             0.99             0.01
414                found      4304       548             0.97             0.03
557157           she was      4294      2455             0.15             0.85
1732          this place      4257      1752             0.91             0.09
876                 feel      4210      1010             0.95             0.05
558452            it was      4154      3794             0.10             0.90
557994              went      4114      3136             0.12             0.88
806                 is a      4074       910             0.95             0.05
1405           the salon      4063      1403             0.92             0.08
1634              i will      4048      1588             0.91             0.09
103               i love      4008       190             0.99             0.01
2144            i wanted      3975      1993             0.89             0.11
857              with my      3927       925             0.95             0.05
1089           have been      3839      1093             0.94             0.06
1579              if you      3753      1440             0.91             0.09
2483             for the      3692      2084             0.87             0.13
557354           i would      3688      2247             0.15             0.85
557697            that i      3646      2500             0.13             0.87
969                style      3609       937             0.94             0.06
558058            when i      3600      2808             0.12             0.88
1645            going to      3571      1409             0.91             0.09
4       highly recommend      3554        32             1.00             0.00
508                super      3527       525             0.97             0.03
1296                sure      3475      1134             0.93             0.07
1115            hair and      3466      1006             0.94             0.06
1695                took      3414      1379             0.91             0.09
557640              know      3402      2281             0.13             0.87
844                staff      3386       793             0.95             0.05
464         professional      3384       464             0.97             0.03
1851                long      3369      1475             0.90             0.10
500                clean      3271       484             0.97             0.03
557331               day      3269      1974             0.15             0.85
1780               right      3229      1363             0.91             0.09
557861            to the      3201      2322             0.13             0.87
2039            with the      3159      1507             0.89             0.11
1742               on my      3158      1310             0.91             0.09
389               she 's      3150       384             0.98             0.02
1518              for my      3077      1137             0.92             0.08
1585            hair cut      3060      1177             0.91             0.09
724              cut and      3013       610             0.96             0.04
558620            do n't      2985      2954             0.09             0.91
1694             getting      2955      1193             0.91             0.09
1386                   &      2940      1006             0.92             0.08
219                thank      2939       228             0.98             0.02
633             've been      2876       516             0.96             0.04
1281                gave      2820       910             0.93             0.07
557419               way      2810      1759             0.14             0.86
1849               had a      2793      1222             0.90             0.10
557293              came      2774      1657             0.15             0.85
170            beautiful      2769       180             0.99             0.01
1367                find      2740       929             0.93             0.07
1771              and it      2719      1141             0.91             0.09
1226          this salon      2694       843             0.93             0.07
561                did a      2685       431             0.97             0.03
129            thank you      2674       146             0.99             0.01
316              exactly      2656       272             0.98             0.02
557314              come      2649      1593             0.15             0.85
1388            was very      2612       894             0.92             0.08
1490              little      2612       951             0.92             0.08
1635                   /      2577      1012             0.91             0.09

In [2]:
Hair_Salons_yelp_poor.sort_values(by='1.0 freq', ascending = False).head(100)

NameError: name 'Hair_Salons_yelp_poor' is not defined

In [ ]:
Fashion_yelp_high.sort_values(by='5.0 freq', ascending = False)

In [ ]:
Fashion_yelp_poor.sort_values(by='1.0 freq', ascending = False).head(100)

In [138]:
Professional_Services_yelp_poor_json = Professional_Services_yelp_poor_json.drop([136,3577,2707,664626,1979,2678])
Professional_Services_yelp_poor_json.sort_values(by='1 freq', ascending = False).head(10)

           term  1 freq  5 freq  highratingscore  poorratingscore
2480    service    8908    7581             0.10             0.90
445           $    5996    1606             0.03             0.97
1022      phone    4776    2213             0.06             0.94
1472     called    4287    2560             0.07             0.93
136         cox    3135     371             0.01             0.99
3577     it was    3005    3433             0.14             0.86
2707     to the    2969    2694             0.11             0.89
664626     work    2900    7039             0.93             0.07
1976    did n't    2855    2069             0.09             0.91
2678     that i    2845    2557             0.11             0.89

In [ ]:
Professional_Services_yelp_poor.sort_values(by='1 freq', ascending = False).head(100)

In [130]:
Professional_Services_yelp_high_json = Professional_Services_yelp_high_json.drop([1777])
Professional_Services_yelp_best_json = Professional_Services_yelp_high_json.sort_values(by='5 freq', ascending = False).head()

              term  1 freq  5 freq  highratingscore  poorratingscore
2721          time    5335    8239             0.89             0.11
302   professional     485    4677             0.98             0.02
2636           new    2438    3861             0.89             0.11
2850          home    2143    3174             0.88             0.12
293       friendly     308    3059             0.98             0.02

In [ ]:
Professional_Services_yelp_high.sort_values(by='5 freq', ascending = False).head()
Professional_Services_yelp_poor_json.sort_values(by='1 freq', ascending = False).head()

In [153]:
df = df.head()
df.to_json('Fashion_yelp_high_rating_words.json', orient='records', lines=True)